"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import sys
from pathlib import Path

from decouple import Csv, config

# Detect `manage.py test` so list-view caching doesn't leak state between
# tests (LocMemCache isn't reset by TestCase's transaction rollback).
TESTING = "test" in sys.argv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="", cast=Csv())

# Render injects its own external hostname at runtime; pick it up
# automatically so it doesn't also have to be set by hand in ALLOWED_HOSTS.
RENDER_EXTERNAL_HOSTNAME = config("RENDER_EXTERNAL_HOSTNAME", default="")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Render (and similar platforms) sit behind a proxy that terminates HTTPS
# and forwards plain HTTP internally, flagging the original scheme via this
# header. Without it, Django can't tell the request was actually HTTPS.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Needed for CSRF checks on HTTPS deployments where the app doesn't already
# know its own public hostname (e.g. Render's *.onrender.com domains).
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=not DEBUG, cast=bool)
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=not DEBUG, cast=bool)
X_FRAME_OPTIONS = "DENY"

# 1 year, once you're confident HTTPS is solid — start lower (e.g. 3600) and
# raise it once verified, since browsers will refuse plain HTTP for this
# long once they've seen the header.
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "library",

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # Order is not a style choice here. LocaleMiddleware reads the session,
    # so it has to come after SessionMiddleware; CommonMiddleware can
    # redirect (APPEND_SLASH) before a language is active, so it has to come
    # after this. In the wrong place the language silently never applies.
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    # A signed-in person's stored language beats whatever the browser asked
    # for. Must be after AuthenticationMiddleware, which is what puts
    # `request.user` there for it to read.
    "library.middleware.UserLanguageMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTH_USER_MODEL = "library.User"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                # LANGUAGE_CODE and LANGUAGE_BIDI in every template, which
                # is what base.html reads to set `lang` and `dir`.
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Organisation branding (name, logo, colours). Must stay
                # available for anonymous users too — the login page uses it.
                "library.context_processors.branding",
                # `layout`: the whole shell, or just the main-content
                # region when an HTMX navigation asks for it.
                "library.context_processors.navigation",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": config("DB_ENGINE", default="django.db.backends.postgresql"),
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
        # All app models are `managed = False` (existing schema), so Django's
        # migrations can't create their tables in a fresh test database.
        # The test DB below is a one-time schema-only clone of production
        # (see docs/DATABASE.md) — always run tests with `--keepdb` so Django
        # reuses it instead of trying to recreate it from scratch.
        "TEST": {
            "NAME": config("DB_TEST_NAME", default="madrasah_library_test"),
        },
    }
}

CACHES = {
    "default": {
        "BACKEND": (
            "django.core.cache.backends.dummy.DummyCache"
            if TESTING
            else "django.core.cache.backends.locmem.LocMemCache"
        ),
        "LOCATION": "madrasah-library-cache",
    }
}
# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

# "en" rather than "en-us": the three offered languages are en/ur/ar, and a
# regional default would make Django resolve `en-us` to `en` on every
# request for nothing.
LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", "English"),
    ("ur", "اردو"),
    ("ar", "العربية"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

# Django's own `ar` locale formats numbers with Eastern Arabic digits
# (٠١٢٣) and dates in a different order. For a library that is wrong: a
# copy code, an ISBN and a loan number are identifiers, not quantities, and
# they must read the same in every language. These modules force Latin
# digits back; the identifiers themselves are additionally wrapped in
# `{% localize off %}` where they are printed.
FORMAT_MODULE_PATH = ["config.formats"]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Media files (user uploads, e.g. book cover images)
# https://docs.djangoproject.com/en/6.1/topics/files/
#
# NOTE: these are served by Django itself (see config/urls.py), which is fine
# for local use and the demo deployment but is not how a busy site should
# serve uploads. Two things to change before relying on this in production:
# put a real web server or CDN in front of MEDIA_URL, and move MEDIA_ROOT to
# durable storage — on a container host with an ephemeral filesystem (Render's
# free tier included) uploaded covers are lost on every redeploy.

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# Largest cover image a user may upload, in bytes.
COVER_IMAGE_MAX_BYTES = 2 * 1024 * 1024

# Branding uploads. A logo is displayed at ~180px wide and a favicon at
# 32px, so both can be much smaller than a book cover.
LOGO_MAX_BYTES = 1 * 1024 * 1024
FAVICON_MAX_BYTES = 256 * 1024


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}
